export default [
  {
    icon: "streamline-flex:dashboard-3",
    key: "dashboard",
    label: "dashboard.title",
    path: "/dashboard",
    routeName: "dashboard",
    roles: ["admin"],
  },
  {
    icon: "solar:user-id-outline",
    key: "admin_assistants",
    label: "مساعدين الأدمن",
    path: "/users/assistants",
    routeName: "admin_assistants",
    roles: ["admin"],
  },
  {
    icon: "solar:checklist-minimalistic-outline",
    key: "tasks",
    label: "مهام",
    path: "/tasks",
    routeName: "tasks",
    roles: ["admin", "admin_assistant"],
  },
  {
    icon: "solar:users-group-rounded-outline",
    key: "users",
    label: "users.title",
    path: "/users",
    routeName: "users",
    roles: ["admin"],
  },
  {
    icon: "solar:chart-outline",
    key: "admin_consumptions",
    label: "الاستهلاكات",
    path: "/users/consumptions",
    routeName: "users_consumptions",
    roles: ["admin"],
  },
  {
    icon: "solar:clipboard-list-outline",
    key: "reports",
    label: "reports.title",
    path: "/reports",
    routeName: "reports",
    roles: ["admin", "admin_assistant"],
  },
  {
    icon: "solar:settings-outline",
    key: "types_management",
    label: "إدارة الأنواع",
    path: "/settings/types-management",
    routeName: "types_management",
    roles: ["admin"],
  },
  {
    icon: "mdi:sprout",
    key: "farms",
    label: "farms.title",
    path: "/farms",
    routeName: "farms",
    roles: ["farm_owner"],
  },
  {
    icon: "solar:chart-outline",
    key: "farm_consumptions",
    label: "الاستهلاكات",
    path: "/farms/consumptions",
    routeName: "farm_consumptions",
    roles: ["farm_owner"],
  },
  {
    icon: "solar:checklist-minimalistic-outline",
    key: "farm_tasks",
    label: "مهام زراعية",
    path: "/farms/tasks",
    routeName: "farm_tasks",
    roles: ["farm_owner"],
  },
];