export default [
  {
    icon: "streamline-flex:dashboard-3",
    key: "dashboard",
    label: "dashboard.title",
    path: "/dashboard",
    routeName: "dashboard",
    roles: ["admin"],
  },
  {
    icon: "solar:users-group-rounded-outline",
    key: "users",
    label: "users.title",
    path: "/users",
    routeName: "users",
    roles: ["admin"],
  },
  {
    icon: "solar:clipboard-list-outline",
    key: "reports",
    label: "reports.title",
    path: "/reports",
    routeName: "reports",
    roles: ["admin"],
  },
  {
    icon: "solar:settings-outline",
    key: "types_management",
    label: "إدارة الأنواع",
    path: "/settings/types-management",
    routeName: "types_management",
    roles: ["admin"],
  },
  {
    icon: "mdi:sprout",
    key: "farms",
    label: "farms.title",
    path: "/farms",
    routeName: "farms",
    roles: ["farm_owner"],
  },
  {
    icon: "solar:chart-outline",
    key: "farm_consumptions",
    label: "الاستهلاكات",
    path: "/farms/consumptions",
    routeName: "farm_consumptions",
    roles: ["farm_owner"],
  },
];